spring:
  application:
    name: inventory-module
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.dealership: DEBUG
    org.springframework.security: INFO
    org.flywaydb: DEBUG